##-!ENCRYPT
##        encryptors:
##          aes_encryptor:
##            type: AES
##            props:
##              aes-key-value: 123456abc
##        tables:
##          t_user:
##            columns:
##              pwd:
##                plainColumn: pwd
##                cipherColumn: pwd_cipher
##                encryptorName: aes_encryptor
##        queryWithCipherColumn: false
##
#
#
#
#spring:
##    profiles:
##      include: common-local
#  shardingsphere:
##      datasource:
##        names: write-ds,read-ds-0
##        write-ds:
##          jdbcUrl: jdbc:mysql://mysql.local.test.glzhapp.com:23306/test?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
##          type: com.zaxxer.hikari.HikariDataSource
##          driver-class-name: com.mysql.cj.jdbc.Driver
##          username: root
##          password: Qq2e66hxnNd9MdNc
#          connectionTimeoutMilliseconds: 3000
#          idleTimeoutMilliseconds: 60000
#          maxLifetimeMilliseconds: 1800000
#          maxPoolSize: 50
#          minPoolSize: 1
#          maintenanceIntervalMilliseconds: 30000
##        read-ds-0:
##          jdbcUrl: jdbc:mysql://mysql.local.test.read1.glzhapp.com:23306/test?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
##          type: com.zaxxer.hikari.HikariDataSource
##          driver-class-name: com.mysql.cj.jdbc.Driver
##          username: root
##          password: Qq2e66hxnNd9MdNc
##          connectionTimeoutMilliseconds: 3000
##          idleTimeoutMilliseconds: 60000
##          maxLifetimeMilliseconds: 1800000
##          maxPoolSize: 50
##          minPoolSize: 1
##          maintenanceIntervalMilliseconds: 30000
#    rules:
##        readwrite-splitting:
##          data-sources:
##            glapp:
##              write-data-source-name: write-ds
##              read-data-source-names:
##                - read-ds-0
##              load-balancer-name: roundRobin # 负载均衡算法名称
##          load-balancers:
##            roundRobin:
##              type: ROUND_ROBIN # 一共两种一种是 RANDOM（随机），一种是 ROUND_ROBIN（轮询）
#      encrypt:
#        encryptors:
#          aes_encryptor:
#            type: AES
#            props:
#              aes-key-value: 123456abc
#          tables:
#            t_user:
#              columns:
#                pwd:
#                  plainColumn: pwd
#                  cipherColumn: pwd_cipher
#                  encryptorName: aes_encryptor
#          queryWithCipherColumn: false
#
##
##        encryptors:
##          pwd-encryptor:
##            props:
##              aes-key-value: 123456abc
##            type: AES
##        tables:
##          t_user:
##            columns:
##              pwd: # pwd 与 pwd_cipher 的转换映射
##                plain-column: pwd # 原文列名称
##                cipher-column: pwd_cipher # 加密列名称
##                encryptor-name: pwd-encryptor # 加密算法名称（名称不能有下划线）
##        queryWithCipherColumn: false # 是否使用加密列进行查询。在有原文列的情况下，可以使用原文列进行查询
